### ISSUE TITLE
Crash at startup(fabric)

### ISSUE THREAD

**Issue by Indiglowr** [AkashiiKun/MoreAxolotlVariantsMod-Common#1]
i updated to the latest fabric version (1.0.7) and now my game crashes on start-up. The log looks like it's saying there was some sort of injection problem
[latest.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/7798194/latest.log)
.

**Comment by AkashiiKun** [comment]
Thanks for reporting, i am fixing the issue.

**Comment by AkashiiKun** [comment]
It should be fixed in this update. Please check out and if you see any other issue tell me.
https://www.curseforge.com/minecraft/mc-mods/mavm/files/3590362

**Comment by Indiglowr** [comment]
thank you it appears to be fixed.
