### ISSUE TITLE
can't place Axolotls after picking them up

### ISSUE THREAD

**Issue by Zelioth** [AkashiiKun/MoreAxolotlVariantsMod-Common#11]
I'm using your latest version on forge 43.1.2 in 1.19.2. I have a public server and single player issue that when these cute little guys are picked up in buckets they can't be placed down. I looked for a config but couldn't locate one. any advice

**Comment by AkashiiKun** [comment]
Just describing the issue doesn't help at all. Could you provide a log? Anyways, that's not an issue with my mod, most likely has to do with another mod you're using that modifies bucket behaviors as stated on #5.

**Comment by AkashiiKun** [comment]
Why i say it has to be with another mod? Simple, my mod extends the vanilla variants list, doesn't change anything else.

**Comment by AkashiiKun** [comment]
Closing as there is no further response.
