### ISSUE TITLE
Interested in talking in discord

### ISSUE THREAD

**Issue by Danjhop4** [AkashiiKun/MoreAxolotlVariantsMod-Common#12]
https://github.com/Danjhop4/message 
here’s my dm I uploaded to a private repository 
Interest in a 3D biomes mod for 1.17 but for multinoise not the normal gen

**Comment by Danjhop4** [comment]
Hope you can open it

**Comment by Danjhop4** [comment]
Added you to viewing list

**Comment by AkashiiKun** [comment]
Not interested.
