### ISSUE TITLE
Crash on Startup (Code Exit 1)

### ISSUE THREAD

**Issue by xd4rkzghost01** [AkashiiKun/MoreAxolotlVariantsMod-Common#15]
As the title said, the game grash uppon startup. It doesnt load at all.
I was trying to load it by CurseforgeAPP and this dont work. So i came on the website, trying to find the files updates (even the API) but it still dont work.
Can you check this, i love those axolot variant you all made.

Latest Log
[latest.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10405877/latest.log)

**Comment by AkashiiKun** [comment]
What version of MAVM you're using?

**Comment by xd4rkzghost01** [comment]
It is the one available on CurseForge App: mav-1.2.0mc1.19.2
So i presume it only for 1.19.2 but i was on 19.3
But your Api is for 19.3. I saw this with a couple of mod too. They are available for 1.19.3 on Curseforge but when downloaded (or if we check the version available) they for the oldest version.

**Comment by AkashiiKun** [comment]
My mod has a 1.19.3 version.

**Comment by AkashiiKun** [comment]
More Axolotl Variants Mod (1.19.2 & 1.19.3):
https://www.curseforge.com/minecraft/mc-mods/mavm/files/4108012
The API: (1.19.3 only):
https://www.curseforge.com/minecraft/mc-mods/mavapi/files/4166341

**Comment by xd4rkzghost01** [comment]
So I've tried again and it doesnt work. I've download them from the link you gave me and it still give me the same error. If i remove them from the mods folders everything works well.
I cant get a crash log but i got another latest.

[withaxolot.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10414852/withaxolot.log)

Edit: i just have another log with only your mod. Nothing else. 
[onlyaxolot.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10414861/onlyaxolot.log)

And Both are with Forge 44.1.5

**Comment by AkashiiKun** [comment]
Could you download the new update i've done and check if it's fixed? Thank you for the report.

**Comment by xd4rkzghost01** [comment]
Seems like that was the API. It's all good now :D And everything work perfectly.
![AxolotWork](https://user-images.githubusercontent.com/63568312/212449974-b9a5ff5d-6775-4c0d-96ff-09df7b7edbe7.png)

I'd love to have that time and the patience learning coding like that. You did a great job!
Thx And Good luck with the futures update \(^^)/
