### ISSUE TITLE
Crashes on Startup - Fabric 1.19.3

### ISSUE THREAD

**Issue by PastellePixie** [AkashiiKun/MoreAxolotlVariantsMod-Common#16]
[crash-2023-01-14_12.04.07-client.txt](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10418300/crash-2023-01-14_12.04.07-client.txt)

Crashes on startup.

**Comment by AkashiiKun** [comment]
Fixed, was related to the API. Please download the latest version of More Axolotl Variants API (1.0.3). Will take some time to appear on CurseForge but is already available on Modrinth. Thanks for the report and enjoy my mod ^^.
