### ISSUE TITLE
Compat with Xaeros MiniMap

### ISSUE THREAD

**Issue by ItsTruffle** [AkashiiKun/MoreAxolotlVariantsMod-Common#17]
i got a crash report for xaeros minimap saying it had trouble loading "golden axolotl"
[crash-2023-01-30_18.03.21-client.txt](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10547076/crash-2023-01-30_18.03.21-client.txt)

**Comment by AkashiiKun** [comment]
Can't add support for xaero's minimap as it isn't open source.
