### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by SmartSalo** [AkashiiKun/MoreAxolotlVariantsMod-Common#2]
server log (client with same errors)
[2022-01-01-7.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/7798185/2022-01-01-7.log)

**Comment by bessiq** [comment]
Same issue - version 1.07 on Fabric 1.18.1. Was hesitant to update since no change log was provided, but tried anyway. Reverting back to 1.0.6a resolved the issue for now.

**Comment by AkashiiKun** [comment]
Thanks for reporting, currently fixing the issue.

**Comment by AkashiiKun** [comment]
a fix should be on curseforge in a couple of minutes.

**Comment by AkashiiKun** [comment]
Please test if this fixes your issue, thanks.
https://www.curseforge.com/minecraft/mc-mods/mavm/files/3590362
