### ISSUE TITLE
Game crashes when loading MAVM axolotl

### ISSUE THREAD

**Issue by m0thknight** [AkashiiKun/MoreAxolotlVariantsMod-Common#22]
[crash-2023-03-09_19.52.12-client.txt](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10938295/crash-2023-03-09_19.52.12-client.txt)

I know this is caused by an incompatibility with More axolotls, but when I reported it to them they said to report it here.

**Comment by AkashiiKun** [comment]
Can't fix as my mod uses an API (https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common) that changes how axolotl registry works.
