### ISSUE TITLE
Visual Overhaul changes affects Axolol Bucket overlay

### ISSUE THREAD

**Issue by Shibva** [AkashiiKun/MoreAxolotlVariantsMod-Common#23]
At first I thought the bucket renderers are broken, but then after trying something that I learned about the mod Visual Overhaul (a mod that adds some better visuals) is whats screwing up the axolol color overlay.

One of the things Visual Overhaul does is include a method for having water blending based on what biome your in. It appears that this process messes up the color overlay that is also displayed on the axolotl. Disabling this fixes the issue but also messes with the water buckets color. 

![image](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/assets/38770780/522cf698-1fee-4a02-bb58-6a4c6745ca1c)
(Advanced Tooltips is being used to show the contents of the bucket with a visual)

**Comment by AkashiiKun** [comment]
Wrong repository, it's an issue between Visual Overhaul and [More Axolotl Variants API](https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common).
