### ISSUE TITLE
Commands Broken

### ISSUE THREAD

**Issue by Dolphinways** [AkashiiKun/MoreAxolotlVariantsMod-Common#24]
when using a command (example: /summon axolotl ~ ~ ~ {Variant:4} ) it will only summon red/pink axolotl (like in minecraft: BE)

**Comment by AkashiiKun** [comment]
Minecraft version? Also have you checked the mod's description?

**Comment by DomiIRL** [comment]
> when using a command (example: /summon axolotl ~ ~ ~ {Variant:4} ) it will only summon red/pink axolotl (like in minecraft: BE)

You have to use strings as variants. Its "minecraft:lucy" for the pink one for example
