### ISSUE TITLE
Glow axolotl?

### ISSUE THREAD

**Issue by allanonmage** [AkashiiKun/MoreAxolotlVariantsMod-Common#26]
I came across your mod on Modrinth.  Do all the different axolotls spawn in all the normal places, or are they biome specific?

Do the glow variants..... glow?  Will they glow if a mod makes glowsquid glow?

**Comment by AkashiiKun** [comment]
It seems that you haven't read the mod's description but i'll answer anyways.

_Do all the different axolotls spawn in all the normal places, or are they biome specific?_
All of them but the glowxolotl and skulk spawn naturally. The other two can only be obtained via breeding like the blue axolotl.

_Do the glow variants..... glow?_
First of all, there's only one variant that glows and it's called glowxolotl.
The glowxolotl glows like glowsquids do in vanilla. Even has the glowsquid particles and sounds.

_Will they glow if a mod makes glowsquid glow?_

No.
