### ISSUE TITLE
Visual Bug with the Bucket of Axolotl item

### ISSUE THREAD

**Issue by SimulationOfMario** [AkashiiKun/MoreAxolotlVariantsMod-Common#28]
I think it is an incompatibility with another mod but I am not sure, the only one I can think of that is the cause is Quark but I don't know.

![2024-06-20_13 14 38](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/assets/124881638/19a74f22-81a6-4577-8c3e-f56d1378415d)

![2024-06-20_13 14 55](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/assets/124881638/0330431f-c8ac-4e0d-8f3e-884654216bb4)

**Comment by lSherozl** [comment]
Can confirm this issue too

**Comment by AkashiiKun** [comment]
With just pictures i can't fix anything.
What modloader? Mod list? MAVAPI Version? Minecraft version?

Anyways, if it's forge, most likely is an incompatibility due to sinytra connector + Forgified Fabric API.

**Comment by lSherozl** [comment]
> With just pictures i can't fix anything. What modloader? Mod list? MAVAPI Version? Minecraft version?
> 
> Anyways, if it's forge, most likely is an incompatibility due to sinytra connector + Forgified Fabric API.

I am using connector and it is 1.20.1 forge version, there are no variants of axolotl, on the version im using, unless im searching for them wrong

**Comment by AkashiiKun** [comment]
Sinytra Connector not supported. Also 1.20.1 support has been dropped.

**Comment by lSherozl** [comment]
If you say so but it has issues without connector too

**Comment by SimulationOfMario** [comment]
So sad that still don't support 1.20.1

**Comment by SimulationOfMario** [comment]
I use Forge, yep, but this issue didn't happen before but after I installed another mods I think, it can be Quark but I'm not sure

**Comment by T3chDelicious** [comment]
Just to let you know: had the same issue with missing bucket textures (playing on Forge 1.20.1 with latest Sinytra Connector). Reverting mavm to 1.2.4 and mavapi to 1.1.2 fixed it for me.

**Comment by T3chDelicious** [comment]
Just to let you know: had the same issue with missing bucket textures (playing on Forge 1.20.1 with latest Sinytra Connector). Reverting the versions from mavm to 1.2.4 and mavapi to 1.1.2 fixed it for me.

**Comment by SimulationOfMario** [comment]
Thank you very much for the existence of people like you! 🙏🏻

That will probably fix it because at the time I was playing with the previous version and I remember that the cubes looked good...

**Comment by T3chDelicious** [comment]
You're welcome. A little side note - Quark is also in my mod list and there's an option set to true by default in the config regarding bucket textures. I have set this option to false so I don't know what happens when it's on.
