### ISSUE TITLE
Game isn't loading.

### ISSUE THREAD

**Issue by NedenBurayaBaktin** [AkashiiKun/MoreAxolotlVariantsMod-Common#3]
I want to play the Better Minecraft modpack on a server but it seems like this mod is causing an issue. Everytime the loading stick on the opening screen finishes it starts all over again and this continues infinitely. But when I drag the mod out of the folder everything is fine.

**Comment by AkashiiKun** [comment]
Could you provide a log file?

**Comment by NedenBurayaBaktin** [comment]
> Could you provide a log file?

Oh, no thanks I fixed it
