### ISSUE TITLE
Breeding Variants 

### ISSUE THREAD

**Issue by baicat02** [AkashiiKun/MoreAxolotlVariantsMod-Common#4]
Hi there, 
I have two axolotls, one cyan and one green. When breeding them, I am only getting the two variants that I am breeding with (so I’m only getting cyan and green babies) and I have tried many times. I have seen the black one in lush caves, so I am able to find other variants, just not breed any other colors from the two I have. I do have the latest version installed. 

I found another color variant and I’m still having the same issue. Even with breeding two of the same color, only getting that variant.

**Comment by AkashiiKun** [comment]
that's how it works, you have to find all the ones but glowxolotl, skulk and blue.

**Comment by AkashiiKun** [comment]
Then you have to breed them until you get the non natural ones, you'll get one of the parents' variant but a chance to get a non natural axolotl variants.
