### ISSUE TITLE
Unable to place bucket of axolotol with this mod

### ISSUE THREAD

**Issue by doggos2** [AkashiiKun/MoreAxolotlVariantsMod-Common#5]
I'm playing better minecraft, and this mod is a part of it. I have an axoltol from this mod (The teal one if thats important) and it is not letting me place the bucket of axolotol down. I am able to place vanilla axolotols like pink and yellow, but not this one. I'm not sure what is causing this but its affecting my playthrough

**Comment by AkashiiKun** [comment]
Could you provide a log? Also, what version and modloader?

**Comment by omggg218** [comment]
Hi there, I also have this issue with the Better Minecraft modpack, but unlike the other person i can't place down both the vanila ones and the ones from the mod, tested on both server and singleplayer. I'm using forge and  1.0.7a version of the mod.

**Comment by AkashiiKun** [comment]
Once again, i do need logs, just explaining the issue doesn't help at all.

**Comment by omggg218** [comment]
[latest.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/8460079/latest.log)

**Comment by omggg218** [comment]
sorry for that, don't know if this is the one you need but here.

**Comment by AkashiiKun** [comment]
Could you try this command and tell me if it spawns or not?
/summon minecraft:axolotl ~ ~ ~ {Variant:12b}

**Comment by omggg218** [comment]
it spawned, used a water bucket on it but the bucket of axolotl cannot be used.

**Comment by AkashiiKun** [comment]
Then the problem isn't on my mod side, my mod only adds new axolotl variants, doesn't touch the bucket code or any item. Also logs doesn't provide any error related to your issue.

**Comment by omggg218** [comment]
yeah deleted the mod and its still the same. thanks anyway.
