### ISSUE TITLE
Version 1.0.8 on Fabric 1.18.2-0.14.6 Crashes

### ISSUE THREAD

**Issue by Rage-GitHub** [AkashiiKun/MoreAxolotlVariantsMod-Common#6]
The newest update, 1.0.8, is having some issues on launching the game and causing a [crash](https://gist.github.com/Rage-GitHub/bb3be06262be1fb33e87ceb3fe85d9c4).

> `Mixin apply for mod mavm failed mavm.mixins.json:AxolotlMixin from mod mavm -> net.minecraft.class_5762: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException `

**Comment by Peach774** [comment]
Crashes for forge too. Something is wrong

**Comment by DatuStram** [comment]
Same issue here using the latest version on Fabric.

[Here's a paste of the log](https://www.toptal.com/developers/hastebin/idamutiwuk.http)

**Comment by AkashiiKun** [comment]
Fixed, thanks for reporting.
Fabric:
https://modrinth.com/mod/mavm/version/1.0.8a
https://www.curseforge.com/minecraft/mc-mods/mavm/files/3819281
Forge:
https://modrinth.com/mod/mavm/version/v1.0.8b
https://www.curseforge.com/minecraft/mc-mods/mavm/files/3819284
