### ISSUE TITLE
Infinite Loading screen when PC-Language is set to certain languages

### ISSUE THREAD

**Issue by jacg311** [AkashiiKun/MoreAxolotlVariantsMod-Common#8]
Log:
[latest.log](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/9027644/latest.log)

Steps to reproduce:
- Set language to turkish either through pc settings or jvm flag `-Duser.language=tr`
- Try to start the game with MAVM

Likely Solution:
Specify the Locale that is used when converting the name of the variant to lowercase [here](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/blob/master/Common/src/main/java/io/github/akashiikun/mavm/mixin/VariantMixin.java#L36)
```java
variant.name().toString.toLowerCase(Locale.ROOT)
```
Java uses, by default, the locale of the pc/jvm args for the conversion. This can lead to issues like this when using languages like turkish (and others) where lowercase "i" actually is "ı".
Locale.ROOT is neutral and will correctly convert the string.

**Comment by AkashiiKun** [comment]
Alright, going to apply this patch.
